/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.ImageModel;
import Services.ImageService;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lab656
 */
public class ImageSelectView extends javax.swing.JFrame {

    private final ImageModel _image = new ImageModel();

    private final ImageService _imageService = new ImageService(_image);

    /**
     * Creates new form ImageSelectView
     */
    public ImageSelectView() {
        initComponents();
        SetInvisibleComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectImageBtn = new javax.swing.JButton();
        SelectImageLabel = new javax.swing.JLabel();
        AplyFilterBtn = new javax.swing.JButton();
        AplyFilterLabel = new javax.swing.JLabel();
        BeforeImage = new javax.swing.JLabel();
        AfterImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sobel FIlter");

        SelectImageBtn.setText("Escolher Imagem");
        SelectImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectImageBtnActionPerformed(evt);
            }
        });

        SelectImageLabel.setText("Selecione uma imagem");

        AplyFilterBtn.setText("Aplicar Filtro");
        AplyFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplyFilterBtnActionPerformed(evt);
            }
        });

        AplyFilterLabel.setText("Aplicar Filtro");

        BeforeImage.setBackground(new java.awt.Color(204, 204, 204));
        BeforeImage.setForeground(new java.awt.Color(102, 102, 102));
        BeforeImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BeforeImage.setText("Pré visualização (Escolha uma Imagem)");
        BeforeImage.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null)));

        AfterImage.setBackground(new java.awt.Color(204, 204, 204));
        AfterImage.setForeground(new java.awt.Color(102, 102, 102));
        AfterImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AfterImage.setText("Resultado Final");
        AfterImage.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BeforeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AfterImage, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AplyFilterBtn)
                    .addComponent(SelectImageLabel)
                    .addComponent(SelectImageBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(AplyFilterLabel)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SelectImageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectImageBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AfterImage, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BeforeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(AplyFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AplyFilterBtn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectImageBtnActionPerformed
        // TODO add your handling code here:

        SetInvisibleComponents();

        int selecionado = FileChooser.showDialog(this, "Selecione o arquivo");

        if (selecionado == 1) {
            return;
        }

        System.out.println("SET IMAGE");

        _image.setFile(FileChooser.getSelectedFile());

        SetVisibleComponents();

        System.out.println("START PAINT");

        PaintBefore();

        System.out.println("END SELCTED");

    }//GEN-LAST:event_SelectImageBtnActionPerformed

    private void AplyFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplyFilterBtnActionPerformed
        // TODO add your handling code here:
        PaintAfter(_imageService.AplyFilter());
    }//GEN-LAST:event_AplyFilterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageSelectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageSelectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageSelectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageSelectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageSelectView().setVisible(true);
            }
        });
    }

    private void SetInvisibleComponents() {
        AplyFilterBtn.setVisible(false);
        AplyFilterLabel.setVisible(false);
//        AfterImage.setVisible(false);     
//        BeforeImage.setVisible(false);
    }

    private void SetVisibleComponents() {
        AplyFilterBtn.setVisible(true);
        AplyFilterLabel.setVisible(true);
    }

    private void PaintAfter(ImageModel model) {
        AfterImage.setText("");
        AfterImage.setIcon(new ImageIcon(model.getImage()));
    }

    private void PaintBefore() {
        BeforeImage.setText("");
        BeforeImage.setIcon(new ImageIcon(_image.getImage()));
    }

    final JFileChooser FileChooser = new JFileChooser();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfterImage;
    private javax.swing.JButton AplyFilterBtn;
    private javax.swing.JLabel AplyFilterLabel;
    private javax.swing.JLabel BeforeImage;
    private javax.swing.JButton SelectImageBtn;
    private javax.swing.JLabel SelectImageLabel;
    // End of variables declaration//GEN-END:variables
}
